spring:
  application:
    name: KeyGuard

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha